apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoria-gateway
  namespace: memoria
  labels:
    app: memoria-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memoria-gateway
  template:
    metadata:
      labels:
        app: memoria-gateway
    spec:
      containers:
      - name: memoria-gateway
        image: fatmaellouze03/memoria-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: http
        env:
        # K8s DNS interne : les services se trouvent par leur nom
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: 'http://eureka-server:8761/eureka/'
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
