apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoria-planning
  namespace: memoria
  labels:
    app: memoria-planning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memoria-planning
  template:
    metadata:
      labels:
        app: memoria-planning
    spec:
      containers:
      - name: memoria-planning
        image: fatmaellouze03/memoria-planning:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8091
          name: http
        env:
        # K8s DNS interne : les services se trouvent par leur nom
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: 'http://eureka-server:8761/eureka/'
        - name: SPRING_DATASOURCE_URL
          value: 'jdbc:mysql://mysql-users:3306/users_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef: # récupérer depuis un Secret K8s
              name: mysql-secret
              key: username
              optional: true
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
              optional: true
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"