pipeline {
    agent any
    
    environment {
        IMAGE_NAME = 'oussama433/memoria-backend'
        IMAGE_TAG = 'latest'
        DOCKER_CREDS = credentials('docker-hub-credentials')
    }
    
    stages {
        stage('1 - Checkout') {
            steps {
                git branch: 'devops-oussama',
                    url: 'https://github.com/abirgmd/Esprit-PIDEV-4SAE3-2026-Memoria.git'
                echo "Code recupere depuis GitHub"
            }
        }
        
        stage('2 - Build Maven') {
            steps {
                dir('memoria-backend') {
                    sh 'mvn clean package -DskipTests'
                    echo "Build Maven termine"
                }
            }
        }
        
        stage('3 - Tests') {
            steps {
                dir('memoria-backend') {
                    sh 'mvn test'
                }
            }
        }
        
        stage('4 - Build Docker Image') {
            steps {
                dir('memoria-backend') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                    echo "Image Docker construite"
                }
            }
        }
        
        stage('5 - Push Docker Hub') {
            steps {
                sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                echo "Image publiee sur Docker Hub"
            }
        }
    }
    
    post {
        success {
            echo "Pipeline CI reussi"
        }
        failure {
            echo "Pipeline CI echoue"
        }
    }
}
