apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoria-alerts
  namespace: memoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memoria-alerts
  template:
    metadata:
      labels:
        app: memoria-alerts
    spec:
      containers:
      - name: memoria-alerts
        image: fatmaellouze03/memoria-alerts:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: memoria-alerts
  namespace: memoria
spec:
  selector:
    app: memoria-alerts
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30082
  type: NodePort