apiVersion: v1
kind: Service
metadata:
  name: backend-activite
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: backend-activite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-activite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-activite
  template:
    metadata:
      labels:
        app: backend-activite
    spec:
      containers:
        - name: backend-activite
          image: abirgamoudi123/memoria-backend-activite:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/memoria_db?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
