pipeline {
    agent any
    environment {
        MS_NAME = 'MemoriA-Planning-Service'
        IMAGE_NAME = 'fatmaellouze03/memoria-planning'
        IMAGE_TAG = 'latest'
        DOCKER_CREDS = credentials('docker-hub-credentials')
    }
    stages {
        stage('1 - Checkout') {
            steps {
                git branch: 'fatma-dev',
                    url: 'https://github.com/abirgmd/Esprit-PIDEV-4SAE3-2026-Memoria.git',
                    credentialsId: 'github-credentials'
                echo "Code récupéré depuis GitHub — branche fatma-dev"
            }
        }
        stage('2 - Build Maven') {
            steps {
                dir("MemoriA-dev/MemoriA-Planning-Service") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('3 - Tests') {
            steps {
                dir("MemoriA-dev/MemoriA-Planning-Service") {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit "MemoriA-dev/MemoriA-Planning-Service/target/surefire-reports/*.xml"
                }
                failure {
                    error 'Tests échoués — arrêt du pipeline'
                }
            }
        }
        stage('4 - Docker Build') {
            steps {
                dir("MemoriA-dev/MemoriA-Planning-Service") {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }
        stage('5 - Docker Push') {
            steps {
                sh "echo ${DOCKER_CREDS_PSW} | docker login -u ${DOCKER_CREDS_USR} --password-stdin"
                sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
    }
    post {
        always {
            sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true"
        }
    }
}