apiVersion: v1
kind: Service
metadata:
  name: memoria-alerts
  namespace: memoria
  labels:
    app: memoria-alerts
spec:
  selector:
    app: memoria-alerts
  ports:
  - port: 8092
    targetPort: 8092
    protocol: TCP
    name: http
  type: ClusterIP # interne uniquement, l'API Gateway route vers lui
