apiVersion: v1
kind: Service
metadata:
  name: memoria-planning
  namespace: memoria
  labels:
    app: memoria-planning
spec:
  selector:
    app: memoria-planning
  ports:
  - port: 8091
    targetPort: 8091
    protocol: TCP
    name: http
  type: ClusterIP # interne uniquement, l'API Gateway route vers lui
